import type { Metadata } from "next";
import { listAdminLeads } from "@/lib/seo/leads";
import { displayFramework } from "@/lib/seo/config";
import { listDiscoveredLeads } from "@/lib/seo/local-store";

export const metadata: Metadata = {
  title: "Lead Inbox",
  description: "Captured, discovered and scored leads generated by Kodex acquisition flows.",
  robots: { index: false, follow: false },
};

export default async function AdminLeadsPage() {
  const leads = await listAdminLeads();
  const discoveredLeads = await listDiscoveredLeads();

  return (
    <main className="main">
      <section className="hero">
        <p className="eyebrow">Admin</p>
        <h1>Lead Inbox</h1>
        <p className="summary">
          Review captured leads, live discovery candidates, qualification scores, attribution and routing status from Kodex acquisition journeys.
        </p>
      </section>

      <section className="dashboard-grid" aria-label="Lead summary">
        <div className="metric-tile">
          <span>Total leads</span>
          <strong>{leads.length}</strong>
        </div>
        <div className="metric-tile">
          <span>Discovered</span>
          <strong>{discoveredLeads.length}</strong>
        </div>
        <div className="metric-tile">
          <span>Sales-ready</span>
          <strong>{leads.filter((lead) => lead.score.grade === "sales-ready").length}</strong>
        </div>
        <div className="metric-tile">
          <span>Local storage</span>
          <strong>{leads.filter((lead) => lead.storage === "local").length}</strong>
        </div>
      </section>

      <section className="discovery-results" aria-label="Discovered lead candidates">
        <div className="result-heading">
          <div>
            <p className="eyebrow">Autonomous discovery</p>
            <h2>Lead Candidates</h2>
          </div>
          <a className="secondary-link" href="/admin/seo">Run discovery</a>
        </div>
        {discoveredLeads.length === 0 ? (
          <p className="empty-state">No discovered leads yet. Run discovery from the command center.</p>
        ) : (
          <div className="lead-cards">
            {discoveredLeads.map((lead) => (
              <article className="lead-card" key={lead.id}>
                <div>
                  <span>{lead.source} / {lead.segment}</span>
                  <strong>{lead.companyName}</strong>
                </div>
                <p>{lead.fitReason}</p>
                <dl>
                  <div>
                    <dt>Intent</dt>
                    <dd>{lead.suggestedSearchIntent}</dd>
                  </div>
                  <div>
                    <dt>Page</dt>
                    <dd>{lead.suggestedLandingPage}</dd>
                  </div>
                  <div>
                    <dt>Verified source</dt>
                    <dd><a href={lead.sourceUrl}>{lead.retrievedAt}</a></dd>
                  </div>
                  <div>
                    <dt>Email</dt>
                    <dd>{lead.contactEmail ?? "Not enriched"}</dd>
                  </div>
                  <div>
                    <dt>Confidence</dt>
                    <dd>{lead.confidence}</dd>
                  </div>
                </dl>
              </article>
            ))}
          </div>
        )}
      </section>

      <section className="queue-table" aria-label="Lead inbox">
        <div className="queue-row lead-row queue-head">
          <span>Company</span>
          <span>Framework</span>
          <span>Score</span>
          <span>Action</span>
          <span>Routing</span>
        </div>
        {leads.length === 0 ? (
          <p className="empty-state">No captured leads yet.</p>
        ) : (
          leads.map((lead) => (
            <article className="queue-row lead-row" key={lead.id}>
              <span>
                <strong>{lead.companyName}</strong>
                <br />
                <a href={`mailto:${lead.email}`}>{lead.email}</a>
              </span>
              <span>{displayFramework(lead.framework)}</span>
              <span>{lead.score.score} / 100 {lead.score.grade}</span>
              <span>{lead.score.recommendedAction}</span>
              <span>{lead.routingSummary}</span>
            </article>
          ))
        )}
      </section>
    </main>
  );
}
